spring.application.name=chat_app


# ===============================
# DATASOURCE (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/chatapp?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.mvc.hiddenmethod.filter.enabled=true
spring.main.allow-circular-references=true

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


cloudinary.cloud_name= dmjb3vpbx
cloudinary.api_key=265852843116939
cloudinary.api_secret=NhpNujL_Gcwtf_9u0Euum5-Z_6g

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yassinewada1@gmail.com
spring.mail.password=qvqc txae orcq bpnb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=http://localhost:8080